HEM/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'homes#top'
  devise_for :users
  resources :users, only: %i[show edit update]
  resources :recipes
  resources :draft_ingredients,only:[:create,:update,:destroy]
  resources :ingredients, only: [:update]
  resources :recipe_ingredients,only:[:update,:destroy]
  resources :breakfasts,only: [:new]
  resources :breakfast_recipes,only: [:create,:destroy]
  resources :lunches,only: [:new]
  resources :lunch_recipes,only: [:create,:destroy]
  resources :dinners,only: [:new]
  resources :dinner_recipes,only: [:create,:destroy]
end

HEM/app/models/breakfast.rb
# frozen_string_literal: true

class Breakfast < ApplicationRecord
  has_many :breakfast_ingredients
  has_many :ingredients, through: :breakfast_ingredients
  has_many :breakfast_recipes
  has_many :recipes, through: :breakfast_recipes
  belongs_to :user
end

HEM/app/models/breakfast_recipe.rb
# frozen_string_literal: true

class BreakfastRecipe < ApplicationRecord
  belongs_to :recipe
  belongs_to :breakfast
end

HEM/app/models/dinner.rb
# frozen_string_literal: true

class Dinner < ApplicationRecord
  belongs_to :user
  has_many :dinner_ingredients
  has_many :ingredients, through: :dinner_ingredients
  has_many :dinner_recipes
  has_many :recipes, through: :dinner_recipes
end

HEM/app/models/dinner_ingredient.rb
# frozen_string_literal: true

class DinnerIngredient < ApplicationRecord
  belongs_to :ingredient
  belongs_to :dinner
end

HEM/app/models/dinner_recipe.rb
# frozen_string_literal: true

class DinnerRecipe < ApplicationRecord
  belongs_to :recipe
  belongs_to :dinner
end

HEM/app/models/draft.rb
# frozen_string_literal: true

class Draft < ApplicationRecord
  has_many :ingredients, through: :draft_ingredients
  has_many :draft_ingredients
end

HEM/app/models/draft_ingredient.rb
# frozen_string_literal: true

class DraftIngredient < ApplicationRecord
  belongs_to :user
  belongs_to :ingredient
end

HEM/app/models/ingredient.rb
# frozen_string_literal: true

class Ingredient < ApplicationRecord
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients
  has_many :draft_ingredients
  has_many :drafts, through: :draft_ingredients
end

HEM/app/models/lunch.rb
# frozen_string_literal: true

class Lunch < ApplicationRecord
  has_many :lunch_ingredients
  has_many :ingredients, through: :lunch_ingredients
  has_many :lunch_recipes
  has_many :recipes, through: :lunch_recipes
  belongs_to :user
end

HEM/app/models/lunch_ingredient.rb
# frozen_string_literal: true

class LunchIngredient < ApplicationRecord
  belongs_to :ingredient
  belongs_to :lunch
end

HEM/app/models/lunch_recipe.rb
# frozen_string_literal: true

class LunchRecipe < ApplicationRecord
  belongs_to :recipe
  belongs_to :lunch
end

HEM/app/models/nutrion.rb
# frozen_string_literal: true

class Nutrion < ApplicationRecord
  has_many :ingredients, through: :nutrion_ingredients
  has_many :nutrion_ingredients
end

HEM/app/models/recipe.rb
# frozen_string_literal: true

class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
  has_many :breakfast_recipes
  has_many :breakfasts, through: :breakfast_recipes
  has_many :lunch_recipes
  has_many :lunches, through: :lunch_recipes
  has_many :dinners, through: :dinner_recipes
  has_many :dinner_recipes
  validates :name, presence: true
  validates :name, length: { maximum: 15 }
  validates :method, presence: true
  validates :method, length: { maximum: 300 }
end

HEM/app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  has_many :recipes
  has_many :draft_ingredients
  has_one :breakfast
  has_one :lunch
  has_one :dinner
  attachment :image
  validates :introduction, length: { maximum: 50 }
  validates :name, length: { maximum: 10 }
  validates :name, presence: true
end

HEM/app/helpers/dinners_helper.rb
# frozen_string_literal: true

module DinnersHelper
end

HEM/app/helpers/drafts_helper.rb
# frozen_string_literal: true

module DraftsHelper
end

HEM/app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

HEM/app/helpers/lunches_helper.rb
# frozen_string_literal: true

module LunchesHelper
end

HEM/app/helpers/new_helper.rb
# frozen_string_literal: true

module NewHelper
end

HEM/app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

HEM/app/views/layouts/_footer.html.erb
  <footer class = "mt-5 footer bg-secondary text-center text-white">
    <div class=" footer_content text-center p-3 " style="background-color: rgba(0, 0, 0, 0.2);">
      <b>© 2021 Copyright:HEM</b>
    </div>
  </footer> 

HEM/app/views/layouts/_vitamin_variable.html.erb
<%# 1食で摂取するべき栄養量 %>
<% need_vitaminA = 300 %>
<% need_vitaminB1 = 0.5 %>
<% need_vitaminB2 = 0.6 %>
<% need_vitaminB3 = 6 %>
<% need_vitaminB5 = 2.5 %>
<% need_vitaminB6 = 0.5 %>
<% need_vitaminB12 = 0.8 %>
<% need_vitaminC = 30 %>
<% need_vitaminD = 3 %>
<% need_vitaminE = 2.5 %>

<%#レシピごとに摂取できる栄養素量%>
<% recipe_vitaminA = 0 %>
<% recipe_vitaminB1 = 0 %>
<% recipe_vitaminB2 = 0 %>
<% recipe_vitaminB3 = 0 %>
<% recipe_vitaminB5 = 0 %>
<% recipe_vitaminB6 = 0 %>
<% recipe_vitaminB12 = 0 %>
<% recipe_vitaminC = 0 %>
<% recipe_vitaminD = 0 %>
<% recipe_vitaminE = 0 %>

<% num = 0 %>

<h4 class = "mb-5 mt-5"><span class = "border border-dark pr-4 pl-4 pt-2 pb-2 rounded" >提案レシピ</span></h4>
<table>    
  <tbody>
    <tr>
      <td class = "pb-4 pr-4">不足栄養素</td>
      <td class = "pb-4 pr-4">不足量　</td>
      <td class = "pb-4 pr-4">提案レシピ</td>
    </tr>
    <tr class = "border-top border-bottom  border-dark">
    <% need_vitaminA = need_vitaminA - vitaminA %>
    <% if need_vitaminA > 0 %>
      <td class = "pb-4 pr-4 pt-4"><%= "ビタミンA" %></td>
      <td class = "pb-4 pr-4 pt-4"><%= need_vitaminA.round %><%= "μg" %></td>
      <td class = "pb-4 pr-4 pt-4">
      
      <% num = 0 %>  
      <% @all_recipes.each do |recipe| %>
        <% recipe.ingredients.each do |ingredient| %>
          <% ingredient.recipe_ingredients.each do |recipe_ingredient| %>
            <% recipe_vitaminA += ingredient.vitaminA*recipe_ingredient.quantity %>
          <% end %>
        <% end %>
        <% if need_vitaminA < recipe_vitaminA %>
          <%= num += 1 %>.
          <b><%= link_to "#{recipe.name}", recipe_path(recipe.id),class:"text-dark" %></b>
        <% end %>
        <% break if num ==3%>
        <% recipe_vitaminA = 0 %>
      <% end %>
      </td>
    <% end %>
    </tr>
          
    <tr class="border-top border-bottom  border-dark">
    <% need_vitaminB1 = need_vitaminB1 - vitaminB1 %>
    <% if need_vitaminB1 > 0 %>
      <td class="pb-4 pr-4 pt-4"><%= "ビタミンB1" %></td>
      <td class="pb-4 pr-4 pt-4"><%= need_vitaminB1.round(1) %><%="mg"%></td>
      <td class="pb-4 pr-4 pt-4">
      
      <% num = 0 %>    
      <% @all_recipes.each do |recipe| %>
        <% recipe.ingredients.each do |ingredient| %>
          <% ingredient.recipe_ingredients.each do |recipe_ingredient| %>
            <% recipe_vitaminB1 += ingredient.vitaminB1*recipe_ingredient.quantity %>
          <% end %>
        <% end %>
        <% if need_vitaminB1 < recipe_vitaminB1 %>
          <%= num += 1 %>.
          <b><%= link_to "#{recipe.name}", recipe_path(recipe.id),class:"text-dark" %></b>
        <% end %>
        <% break if num ==3%>
        <% recipe_vitaminB1 = 0 %>
      <% end %>
      </td>
    <% end %>
    </tr>
    
    <tr class="border-top border-bottom  border-dark">
    <% need_vitaminB2 = need_vitaminB2 - vitaminB2 %>
    <% if need_vitaminB2 > 0 %>
      <td class="pb-4 pr-4 pt-4"><%= "ビタミンB2" %></td>
      <td class="pb-4 pr-4 pt-4"><%= need_vitaminB2.round(1) %><%="mg"%></td>
      <td class="pb-4 pr-4 pt-4">
        
      <% num = 0 %>
      <% @all_recipes.each do |recipe| %>
        <% recipe.ingredients.each do |ingredient| %>
          <% ingredient.recipe_ingredients.each do |recipe_ingredient| %>
            <% recipe_vitaminB2 += ingredient.vitaminB2*recipe_ingredient.quantity %>
          <% end %>
        <% end %>
        <% if need_vitaminB2 < recipe_vitaminB2 %>
          <%= num += 1 %>.
          <b><%= link_to "#{recipe.name}", recipe_path(recipe.id),class:"text-dark" %></b>
        <% end %>
        <% break if num ==3%>
        <% recipe_vitaminB2 = 0 %>
      <% end %>
      </td>
    <% end %>
    </tr>
          
    <tr class="border-top border-bottom  border-dark">
    <% need_vitaminB3 = need_vitaminB3 - vitaminB3 %>
    <% if need_vitaminB3 > 0 %>
      <td class="pb-4 pr-4 pt-4"><%= "ビタミンB3" %></td>
      <td class="pb-4 pr-4 pt-4"><%= need_vitaminB3.round(1) %><%="mg"%></td>
      <td class="pb-4 pr-4 pt-4">
        
      <% num = 0 %>
      <% @all_recipes.each do |recipe| %>
        <% recipe.ingredients.each do |ingredient| %>
          <% ingredient.recipe_ingredients.each do |recipe_ingredient| %>
            <% recipe_vitaminB3 += ingredient.vitaminB3*recipe_ingredient.quantity %>
          <% end %>
        <% end %>
        <% if need_vitaminB3 < recipe_vitaminB3 %>
          <%= num += 1 %>.
         <b><%= link_to "#{recipe.name}", recipe_path(recipe.id),class:"text-dark" %></b>
        <% end %>
        <% break if num ==3%>
        <% recipe_vitaminB3 = 0 %>
      <% end %>
      </td>
    <% end %>
    </tr>
    
    <tr class="border-top border-bottom  border-dark">
    <% need_vitaminB5 = need_vitaminB5 - vitaminB5 %>
    <% if need_vitaminB1 > 0 %>
      <td class="pb-4 pr-4 pt-4"><%= "ビタミンB5" %></td>
      <td class="pb-4 pr-4 pt-4"><%= need_vitaminB5.round(1) %><%="mg"%></td>
      <td class="pb-4 pr-4 pt-4">
      
      <% num = 0 %>
      <% @all_recipes.each do |recipe| %>
        <% recipe.ingredients.each do |ingredient| %>
          <% ingredient.recipe_ingredients.each do |recipe_ingredient| %>
            <% recipe_vitaminB5 += ingredient.vitaminB5*recipe_ingredient.quantity %>
          <% end %>
        <% end %>
        <% if need_vitaminB5 < recipe_vitaminB5 %>
          <%= num += 1 %>.
          <b><%= link_to "#{recipe.name}", recipe_path(recipe.id),class:"text-dark" %></b>
        <% end %>
        <% break if num ==3%>
        <% recipe_vitaminB5 = 0 %>
      <% end %>
      </td>
    <% end %>
    </tr>
    
    <tr class="border-top border-bottom border-dark">
    <% need_vitaminB6 = need_vitaminB6 - vitaminB6 %>
    <% if need_vitaminB6 > 0 %>
      <td class="pb-4 pr-4 pt-4"><%= "ビタミンB6" %></td>
      <td class="pb-4 pr-4 pt-4"><%= need_vitaminB6.round(1) %><%="mg"%></td>
      <td class="pb-4 pr-4 pt-4">
      
      <% num = 0 %>
      <% @all_recipes.each do |recipe| %>
        <% recipe.ingredients.each do |ingredient| %>
          <% ingredient.recipe_ingredients.each do |recipe_ingredient| %>
            <% recipe_vitaminB6 += ingredient.vitaminB6*recipe_ingredient.quantity %>
          <% end %>
        <% end %>
        <% if need_vitaminB6 < recipe_vitaminB6 %>
          <%= num += 1 %>.
          <b><%= link_to "#{recipe.name}", recipe_path(recipe.id),class:"text-dark" %></b>
        <% end %>
        <% break if num ==3%>
        <% recipe_vitaminB6 = 0 %>
      <% end %>
      </td>
    <% end %>
    </tr>
    
    <tr class="border-top border-bottom border-dark">
    <% need_vitaminB12 = need_vitaminB12 - vitaminB12 %>
    <% if need_vitaminB12 > 0 %>
      <td class="pb-4 pr-4 pt-4"><%= "ビタミンB12" %></td>
      <td class="pb-4 pr-4 pt-4"><%= need_vitaminB12.round(1) %><%="μg"%></td>
      <td class="pb-4 pr-4 pt-4">
      
      <% num = 0 %>
      <% @all_recipes.each do |recipe| %>
        <% recipe.ingredients.each do |ingredient| %>
          <% ingredient.recipe_ingredients.each do |recipe_ingredient| %>
            <% recipe_vitaminB12 += ingredient.vitaminB12*recipe_ingredient.quantity %>
          <% end %>
        <% end %>
        <% if need_vitaminB12 < recipe_vitaminB12 %>
          <%= num += 1 %>.
          <b><%= link_to "#{recipe.name}", recipe_path(recipe.id),class:"text-dark" %></b>
        <% end %>
        <% break if num ==3%>
        <% recipe_vitaminB12 = 0 %>
      <% end %>
      </td>
    <% end %>
    </tr>
    
    <tr class="border-top border-bottom border-dark">
    <% need_vitaminC = need_vitaminC - vitaminC %>
    <% if need_vitaminC > 0 %>
      <td class="pb-4 pr-4 pt-4"><%= "ビタミンC" %></td>
      <td class="pb-4 pr-4 pt-4"><%= need_vitaminC.round(1) %><%="mg"%></td>
      <td class="pb-4 pr-4 pt-4">
      
      <% num = 0 %>
      <% @all_recipes.each do |recipe| %>
        <% recipe.ingredients.each do |ingredient| %>
          <% ingredient.recipe_ingredients.each do |recipe_ingredient| %>
            <% recipe_vitaminC += ingredient.vitaminC*recipe_ingredient.quantity %>
          <% end %>
        <% end %>
        <% if need_vitaminC < recipe_vitaminC %>
          <%= num += 1 %>.
          <b><%= link_to "#{recipe.name}", recipe_path(recipe.id),class:"text-dark" %></b>
        <% end %>
        <% break if num ==3%>
        <% recipe_vitaminC = 0 %>
      <% end %>
      </td>
    <% end %>
    </tr>
    
    <tr class="border-top border-bottom border-dark">
    <% need_vitaminD = need_vitaminD - vitaminD %>
    <% if need_vitaminD > 0 %>
      <td class="pb-4 pr-4 pt-4"><%= "ビタミンD" %></td>
      <td class="pb-4 pr-4 pt-4"><%= need_vitaminD.round(1) %><%="μg"%></td>
      <td class="pb-4 pr-4 pt-4">
      
      <% num = 0 %>
      <% @all_recipes.each do |recipe| %>
        <% recipe.ingredients.each do |ingredient| %>
          <% ingredient.recipe_ingredients.each do |recipe_ingredient| %>
            <% recipe_vitaminD += ingredient.vitaminD*recipe_ingredient.quantity %>
          <% end %>
        <% end %>
        <% if need_vitaminD < recipe_vitaminD %>
          <%= num += 1 %>.
          <b><%= link_to "#{recipe.name}", recipe_path(recipe.id),class:"text-dark" %></b>
        <% end %>
        <% break if num ==3%>
        <% recipe_vitaminD = 0 %>
      <% end %>
      </td>
    <% end %>
    </tr>
    
    <tr class="border-top border-bottom border-dark">
    <% need_vitaminE = need_vitaminE - vitaminE %>
    <% if need_vitaminE > 0 %>
      <td class="pb-4 pr-4 pt-4"><%= "ビタミンE" %></td>
      <td class="pb-4 pr-4 pt-4"><%= need_vitaminE.round(1) %><%="mg"%></td>
      <td class="pb-4 pr-4 pt-4">
      
      <% num = 0 %>
      <% @all_recipes.each do |recipe| %>
        <% recipe.ingredients.each do |ingredient| %>
          <% ingredient.recipe_ingredients.each do |recipe_ingredient| %>
            <% recipe_vitaminE += ingredient.vitaminE*recipe_ingredient.quantity %>
          <% end %>
        <% end %>
        <% if need_vitaminE < recipe_vitaminE %>
          <%= num += 1 %>.
          <b><%= link_to "#{recipe.name}", recipe_path(recipe.id),class:"text-dark" %></b>
        <% end %>
        <% break if num ==3%>
        <% recipe_vitaminE = 0 %>
      <% end %>
      </td>
    <% end %>
    </tr>
  </tbody>
</table>

HEM/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HEM</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application'%>
    <%= favicon_link_tag('fabicon.png') %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
  </head>

  <body class="background ">
    <% if user_signed_in? %>
      <ul class="list-inline w-100 p-3 bg-secondary">
        <li class="list-inline-item">
          <b><%= link_to "トップ",user_path(current_user),class:"text-white"%></b>
        </li>
        <li class="list-inline-item"><b><%= link_to "レシピ投稿",new_recipe_path,class:"text-white" %></b></li>
        <li class="list-inline-item"><b><%= link_to "レシピ一覧",recipes_path,class:"text-white" %></b></li>
        <li class="list-inline-item"><b><%= link_to "ログアウト", destroy_user_session_path, method: :delete,class:"text-white" %></b></li>
      </ul>
    <% else %>
      <ul class="list-inline w-100 p-3  bg-secondary">
        <li class="list-inline-item ">
          <b><%= link_to "トップ",root_path,class:"text-white"%></b>
        </il>
        <li class="list-inline-item"></i><b><%= link_to "会員登録", new_user_registration_path,class:"text-white" %></b></li>
        <li class="list-inline-item"><b><%= link_to "ログイン", new_user_session_path,class:"text-white" %></b></li>
      </ul>
    <% end %>
    <%= yield %>
  </body>
</html>