HEM/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'homes#top'
  devise_for :users
  resources :users, only: %i[show edit update]
  resources :recipes
  resources :draft_ingredients,only:[:create,:update,:destroy]
  resources :ingredients, only: [:update]
  resources :recipe_ingredients,only:[:update,:destroy]
  resources :breakfasts,only: [:new]
  resources :breakfast_recipes,only: [:create,:destroy]
  resources :lunches,only: [:new]
  resources :lunch_recipes,only: [:create,:destroy]
  resources :dinners,only: [:new]
  resources :dinner_recipes,only: [:create,:destroy]
end

HEM/app/models/breakfast.rb
# frozen_string_literal: true

class Breakfast < ApplicationRecord
  has_many :breakfast_ingredients
  has_many :ingredients, through: :breakfast_ingredients
  has_many :breakfast_recipes
  has_many :recipes, through: :breakfast_recipes
  belongs_to :user
end

HEM/app/models/breakfast_recipe.rb
# frozen_string_literal: true

class BreakfastRecipe < ApplicationRecord
  belongs_to :recipe
  belongs_to :breakfast
end

HEM/app/models/dinner.rb
# frozen_string_literal: true

class Dinner < ApplicationRecord
  belongs_to :user
  has_many :dinner_ingredients
  has_many :ingredients, through: :dinner_ingredients
  has_many :dinner_recipes
  has_many :recipes, through: :dinner_recipes
end

HEM/app/models/dinner_ingredient.rb
# frozen_string_literal: true

class DinnerIngredient < ApplicationRecord
  belongs_to :ingredient
  belongs_to :dinner
end

HEM/app/models/dinner_recipe.rb
# frozen_string_literal: true

class DinnerRecipe < ApplicationRecord
  belongs_to :recipe
  belongs_to :dinner
end

HEM/app/models/draft.rb
# frozen_string_literal: true

class Draft < ApplicationRecord
  has_many :ingredients, through: :draft_ingredients
  has_many :draft_ingredients
end

HEM/app/models/draft_ingredient.rb
# frozen_string_literal: true

class DraftIngredient < ApplicationRecord
  belongs_to :user
  belongs_to :ingredient
end

HEM/app/models/ingredient.rb
# frozen_string_literal: true

class Ingredient < ApplicationRecord
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients
  has_many :draft_ingredients
  has_many :drafts, through: :draft_ingredients
end

HEM/app/models/lunch.rb
# frozen_string_literal: true

class Lunch < ApplicationRecord
  has_many :lunch_ingredients
  has_many :ingredients, through: :lunch_ingredients
  has_many :lunch_recipes
  has_many :recipes, through: :lunch_recipes
  belongs_to :user
end

HEM/app/models/lunch_ingredient.rb
# frozen_string_literal: true

class LunchIngredient < ApplicationRecord
  belongs_to :ingredient
  belongs_to :lunch
end

HEM/app/models/lunch_recipe.rb
# frozen_string_literal: true

class LunchRecipe < ApplicationRecord
  belongs_to :recipe
  belongs_to :lunch
end

HEM/app/models/nutrion.rb
# frozen_string_literal: true

class Nutrion < ApplicationRecord
  has_many :ingredients, through: :nutrion_ingredients
  has_many :nutrion_ingredients
end

HEM/app/models/recipe.rb
# frozen_string_literal: true

class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
  has_many :breakfast_recipes
  has_many :breakfasts, through: :breakfast_recipes
  has_many :lunch_recipes
  has_many :lunches, through: :lunch_recipes
  has_many :dinners, through: :dinner_recipes
  has_many :dinner_recipes
  validates :name, presence: true
  validates :name, length: { maximum: 15 }
  validates :method, presence: true
  validates :method, length: { maximum: 300 }
end

HEM/app/models/recipe_ingredient.rb
# frozen_string_literal: true

class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

HEM/app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  has_many :recipes
  has_many :draft_ingredients
  has_one :breakfast
  has_one :lunch
  has_one :dinner
  attachment :image
  validates :introduction, length: { maximum: 50 }
  validates :name, length: { maximum: 10 }
  validates :name, presence: true
end

HEM/app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only:[:show, :edit, :update]
  before_action :correct_user, only:[:edit, :update]

  def show
    @recipes = @user.recipes
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(current_user.id)
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :image)
  end

  def set_user
    @user = User.find(params[:id])
  end
  
  def correct_user
    redirect_to user_path(current_user) unless @user.id == current_user.id
  end
  
end

HEM/app/helpers/breakfasts_helper.rb
# frozen_string_literal: true

module BreakfastsHelper
end

HEM/app/helpers/dinners_helper.rb
# frozen_string_literal: true

module DinnersHelper
end

HEM/app/helpers/drafts_helper.rb
# frozen_string_literal: true

module DraftsHelper
end

HEM/app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

HEM/app/helpers/lunches_helper.rb
# frozen_string_literal: true

module LunchesHelper
end

HEM/app/helpers/new_helper.rb
# frozen_string_literal: true

module NewHelper
end

HEM/app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

HEM/app/views/users/edit.html.erb
<div class = "col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12- mt-5" >
  <% if @user.errors.any? %>
    <h2><%= "エラーが発生しました" %></h2>
    <ol>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ol>
  <% end %>
  <h3>プロフィール編集</h3>
  <%= form_with model:@user, url:"/users/#{@user.id}", local:true do |f| %>
    <table border=2>
      <tr>
        <td class="p-2">名前</td>
        <td class="p-2"><%= f.text_field:name,style:"width:250px" %></td>
   　  </tr>
   　  <tr>
   　    <td class="p-2">画像  </td>    
   　    <td class="p-2"> <%= attachment_image_tag @user, :image, size: '50x50', fallback: "user.png", class: "mt-2" %><%= f.attachment_field:image, class: "mt-2" %> </td>
      </tr>
      <tr>
        <td class="p-2">紹介文</td>
        <td class="p-2"><%= f.text_area:introduction,style:"width:250px;height:300px;resize:none;"%></td>
      </tr>
    </table>
    <%= f.submit "保存", class: "btn btn-secondary mt-4",style:"width:350px" %>
  <% end %>
</div>
<%= render partial: "layouts/footer" %>

HEM/app/views/users/show.html.erb
<div class = "container-fluid" >
  <div class = "row" >
    <div class = "col-md-8 col-lg-8 col-xl-9">
      <div class = "row">
        <div class = "col-md-12 col-lg-12 col-xl-6">
          <h4 class = "mt-5 mb-5" >
            <span class = "border border-dark pr-5 pl-5 pt-2 pb-2 rounded" >プロフィール<span>
          </h4>
          <div>
            <%= form_with model:@user do |f|%>
              <div class = "mt-2 mb-2 ml-2">
                <%= attachment_image_tag @user, :image, size: '60x60', fallback: "user.png" %>
                <%= f.text_field :name, readonly:true,size:15%>
              </div>　
            <% end %>
          </div>
          <div>
            <textarea readonly style = "height:200px;width:240px;resize:none;"><%= @user.introduction%></textarea>
          </div>
          <% if @user == current_user %>
            <%= link_to edit_user_path, class: 'btn btn-secondary mt-2 mb-2',style:"width:240px" do %>
              <i class="fas fa-edit"></i>　編集
            <% end %>
          <% end %>
          <h4 class = "mt-5 mb-5 w-100" >
            <span class = "border border-dark pr-5 pl-5 pt-2 pb-2 rounded" >　食事記録　<span>
          </h4>
          <h4 class = "mt-4 mb-4" >
            <span class = "border rounded border-dark pr-4 pl-4 pt-2 pb-2">朝食</span>
            <% if @user == current_user %>
              <%= link_to new_breakfast_path, class: 'btn btn-secondary ml-3',style:"width:120px" do %>
                <i class="fas fa-save"></i>　記録
              <% end %>
            <% end %>
          </h4>
          <h4 class="mt-4 mb-4">
            <span class = "border rounded border-dark pr-4 pl-4 pt-2 pb-2">昼食</span>
            <% if @user == current_user %>
              <%= link_to new_lunch_path, class: 'btn btn-secondary ml-3',style:"width:120px" do %>
                <i class="fas fa-save"></i>　記録
              <% end %>
            <% end %>
          </h4>
          <h4 class="mt-4 mb-4">
            <span class = "border rounded border-dark pr-4 pl-4 pt-2 pb-2">夕食</span>
            <% if @user == current_user %>
              <%= link_to new_dinner_path, class: 'btn btn-secondary ml-3',style:"width:120px" do %>
                <i class="fas fa-save"></i>　記録
              <% end %>
            <% end %>
          </h4>
        </div>
        <div class = "col-md-12 col-lg-12 col-xl-6">
          <h3 class = "mt-5 mb-5">
            <span class = "border border-dark  pr-4 pl-4 pt-2 pb-2 rounded">　レシピ一覧　<span>
          </h3>
          <table>
            <thead>
              <tr>
                <td class = "pb-2">レシピ名</td>
                <td>　</td>
              </tr>
            </thead>
            <tbody>
            <% @recipes.each do |recipe| %>
              <tr class = "border-bottom border-top border-dark">
                <% if recipe.user == current_user %>
                  <td class = "pt-2 pb-2 w-50"><%= link_to "#{recipe.name}",recipe_path(recipe),class:"text-dark" %></td>
                  <td class = "pt-2 pb-2">　<%= link_to "編集", edit_recipe_path(recipe.id), class: "btn btn-secondary p-1" %></td>
                  <td class = "pt-2 pb-2">　<%= link_to "削除", recipe_path(recipe.id), method: :delete, class: "btn btn-dark p-1" %></td>
                <% else %>
                  <td class = "pt-2 pb-2 w-100"><%= link_to "#{recipe.name}",recipe_path(recipe) %></td>
                <% end %>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class = "col-md-4 col-lg-4 col-xl-3 border1">
      <h4 class = "mb-5 mt-5"><span class = "border border-dark rounded pt-2 pb-2 pr-3 pl-3">★使用方法</span></h4>
      <h4>1.食事をレシピとして投稿</h4>
      <h4>2.レシピを食事記録に残す</h4>
      <h4>3.栄養を補うレシピが表示</h4>
    </div>
  </div>
</div>
<%= render partial: "layouts/footer" %>