HEM/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'homes#top'
  devise_for :users
  resources :users, only: %i[show edit update]
  resources :recipes
  resources :draft_ingredients,only:[:create,:update,:destroy]
  resources :ingredients, only: [:update]
  resources :recipe_ingredients,only:[:update,:destroy]
  resources :breakfasts,only: [:new]
  resources :breakfast_recipes,only: [:create,:destroy]
  resources :lunches,only: [:new]
  resources :lunch_recipes,only: [:create,:destroy]
  resources :dinners,only: [:new]
  resources :dinner_recipes,only: [:create,:destroy]
end

HEM/app/models/breakfast.rb
# frozen_string_literal: true

class Breakfast < ApplicationRecord
  has_many :breakfast_ingredients
  has_many :ingredients, through: :breakfast_ingredients
  has_many :breakfast_recipes
  has_many :recipes, through: :breakfast_recipes
  belongs_to :user
end

HEM/app/models/breakfast_recipe.rb
# frozen_string_literal: true

class BreakfastRecipe < ApplicationRecord
  belongs_to :recipe
  belongs_to :breakfast
end

HEM/app/models/dinner.rb
# frozen_string_literal: true

class Dinner < ApplicationRecord
  belongs_to :user
  has_many :dinner_ingredients
  has_many :ingredients, through: :dinner_ingredients
  has_many :dinner_recipes
  has_many :recipes, through: :dinner_recipes
end

HEM/app/models/dinner_ingredient.rb
# frozen_string_literal: true

class DinnerIngredient < ApplicationRecord
  belongs_to :ingredient
  belongs_to :dinner
end

HEM/app/models/dinner_recipe.rb
# frozen_string_literal: true

class DinnerRecipe < ApplicationRecord
  belongs_to :recipe
  belongs_to :dinner
end

HEM/app/models/draft.rb
# frozen_string_literal: true

class Draft < ApplicationRecord
  has_many :ingredients, through: :draft_ingredients
  has_many :draft_ingredients
end

HEM/app/models/draft_ingredient.rb
# frozen_string_literal: true

class DraftIngredient < ApplicationRecord
  belongs_to :user
  belongs_to :ingredient
end

HEM/app/models/ingredient.rb
# frozen_string_literal: true

class Ingredient < ApplicationRecord
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients
  has_many :draft_ingredients
  has_many :drafts, through: :draft_ingredients
end

HEM/app/models/lunch.rb
# frozen_string_literal: true

class Lunch < ApplicationRecord
  has_many :lunch_ingredients
  has_many :ingredients, through: :lunch_ingredients
  has_many :lunch_recipes
  has_many :recipes, through: :lunch_recipes
  belongs_to :user
end

HEM/app/models/lunch_ingredient.rb
# frozen_string_literal: true

class LunchIngredient < ApplicationRecord
  belongs_to :ingredient
  belongs_to :lunch
end

HEM/app/models/lunch_recipe.rb
# frozen_string_literal: true

class LunchRecipe < ApplicationRecord
  belongs_to :recipe
  belongs_to :lunch
end

HEM/app/models/nutrion.rb
# frozen_string_literal: true

class Nutrion < ApplicationRecord
  has_many :ingredients, through: :nutrion_ingredients
  has_many :nutrion_ingredients
end

HEM/app/models/recipe.rb
# frozen_string_literal: true

class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
  has_many :breakfast_recipes
  has_many :breakfasts, through: :breakfast_recipes
  has_many :lunch_recipes
  has_many :lunches, through: :lunch_recipes
  has_many :dinners, through: :dinner_recipes
  has_many :dinner_recipes
  validates :name, presence: true
  validates :name, length: { maximum: 15 }
  validates :method, presence: true
  validates :method, length: { maximum: 300 }
end

HEM/app/models/recipe_ingredient.rb
# frozen_string_literal: true

class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

HEM/app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  has_many :recipes
  has_many :draft_ingredients
  has_one :breakfast
  has_one :lunch
  has_one :dinner
  attachment :image
  validates :introduction, length: { maximum: 50 }
  validates :name, length: { maximum: 10 }
  validates :name, presence: true
end

HEM/app/controllers/breakfasts_controller.rb
# frozen_string_literal: true
class BreakfastsController < ApplicationController
  def new
    @breakfast = Breakfast.new
    @search_recipes = Recipe.search(params[:search])
    @search_recipes = @search_recipes.page(params[:page]).per(5)
    @all_recipes = Recipe.all
  end
end

HEM/app/helpers/breakfasts_helper.rb
# frozen_string_literal: true

module BreakfastsHelper
end

HEM/app/helpers/dinners_helper.rb
# frozen_string_literal: true

module DinnersHelper
end

HEM/app/helpers/drafts_helper.rb
# frozen_string_literal: true

module DraftsHelper
end

HEM/app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

HEM/app/helpers/lunches_helper.rb
# frozen_string_literal: true

module LunchesHelper
end

HEM/app/helpers/new_helper.rb
# frozen_string_literal: true

module NewHelper
end

HEM/app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

HEM/app/views/breakfasts/new.html.erb
<div class =  "container-fluid">
  <div class = "row">
    <div class = "col-md-8 col-lg-8 col-xl-9">
      <div class = "row">
        <div class = "col-md-12 col-lg-12 col-xl-4">
          <h4 class = "mt-5 mb-5"><span class = "border border-dark pr-3 pl-3 pt-2 pb-2 rounded" >メニュー検索</span></h4>
          <%= form_tag(new_breakfast_path, :method=>"get" )do %>
            <%= text_field_tag :search,"",class:"rounded mt-3",style:"width:180px" %>
            <br><%= submit_tag "Serch",class:"rounded btn btn-secondary mt-3",style:"width:180px" %>
          <% end %>
          <table>
            <tr>
              <td></td>
              <td></td>
            </tr>
          <% @search_recipes.each do |recipe| %>
            <tr>
              <td>
                <div class = "pt-2 pb-2"><%= link_to "#{recipe.name}", recipe_path(recipe.id),class:"text-dark" %></div>
              </td>
              <td>
                <div class = "a d-flex align-items-center">
                  <%= button_to "追加", {controller: 'breakfast_recipes', action: 'create' }, {method: :post,params: {recipe_id: recipe.id}} %></br>
                </div>
                <div></div>
              </td>
            </tr>
          <% end %>
          </table>
          <div class = "pt-2"><%= paginate @search_recipes %></div>
          <h4 class = "mb-5 mt-5"><span class = "border border-dark pr-4 pl-4 pt-2 pb-2 rounded" >使用レシピ</span></h4>
          <table>
            <thead>
              <tr>
                <td class = "pb-4 pr-4">レシピ名</td>
                <td class = "pb-4 pr-4">削除</td>
              </tr>
            </thead>
            <tbody>
            <% breakfast = current_user.breakfast%>
            <% unless breakfast.nil? %>
              <% unless breakfast.breakfast_recipes.nil? %>
                <% breakfast_recipes = breakfast.breakfast_recipes %>
                <% breakfast_recipes.each do |breakfast_recipe| %>
                  <tr class = "border-top border-bottom border-dark">
                    <td class = "pb-4 pr-4 pt-4"><%= breakfast_recipe.recipe.name %></td>
                    <td class = "pb-4 pr-4 pt-4"><%= link_to "削除", breakfast_recipe_path(breakfast_recipe.id), method: :delete,class:"btn btn-dark" %></td>
                  </tr>
                <% end %>
              <% end %>
            <% end %>
            </tbody>
          </table>
        </div>
        <% vitaminA = 0 %>
        <% vitaminB1 = 0 %>
        <% vitaminB2 = 0 %>
        <% vitaminB3 = 0 %>
        <% vitaminB5 = 0 %>
        <% vitaminB6 = 0 %>
        <% vitaminB12 = 0 %>
        <% vitaminC = 0 %>
        <% vitaminD = 0 %>
        <% vitaminE = 0 %>
        
        <% user_breakfast = current_user.breakfast %>
        <% unless user_breakfast.nil? %>
          <% user_breakfast.recipes.each do |breakfast_recipe| %>
            <% breakfast_recipe.ingredients.each do |breakfast_ingredient| %>
              <% breakfast_ingredient.recipe_ingredients.each do |recipe_ingredient|  %>
                <% vitaminA += breakfast_ingredient.vitaminA*recipe_ingredient.quantity %>
                <% vitaminB1 += breakfast_ingredient.vitaminB1*recipe_ingredient.quantity %>
                <% vitaminB2 += breakfast_ingredient.vitaminB2*recipe_ingredient.quantity %>
                <% vitaminB3 += breakfast_ingredient.vitaminB3*recipe_ingredient.quantity %>
                <% vitaminB5 += breakfast_ingredient.vitaminB5*recipe_ingredient.quantity %>
                <% vitaminB6 += breakfast_ingredient.vitaminB6*recipe_ingredient.quantity %>
                <% vitaminB12 += breakfast_ingredient.vitaminB12*recipe_ingredient.quantity %>
                <% vitaminC += breakfast_ingredient.vitaminC*recipe_ingredient.quantity %>
                <% vitaminD += breakfast_ingredient.vitaminD*recipe_ingredient.quantity %>
                <% vitaminE += breakfast_ingredient.vitaminE*recipe_ingredient.quantity %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
        <div class = "col-md-12 col-lg-12 col-xl-6">
          <%= render partial: "layouts/vitamin_variable", locals: 
          { vitaminA: vitaminA,vitaminB1: vitaminB1 ,vitaminB2: vitaminB2,vitaminB3: vitaminB3,vitaminB5: vitaminB5,
          vitaminB6: vitaminB6,vitaminB12: vitaminB12,vitaminC: vitaminC,vitaminD: vitaminD,vitaminE: vitaminE}%>
       </div>
     </div>
   </div>
   <div class = "col-md-4 col-lg-4 col-xl-3 border1">
     <h4 class = "mb-5 mt-5"><span class = "border border-dark rounded pt-2 pb-2 pr-3 pl-3">★使用方法</span></h4>
     <h4>1.使用したレシピを検索</h4>
     <h4>➡追加</h4>
     <h4>2.栄養を補うレシピが表示</h4>
     <h4>3.レシピ名をクリック</h4>
     <h4>➡詳細チェック</h4>
   </div>
  </div>
</div>
<%= render partial: "layouts/footer" %>