HEM/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'homes#top'
  devise_for :users
  resources :users, only: %i[show edit update]
  resources :recipes
  resources :draft_ingredients,only:[:create,:update,:destroy]
  resources :ingredients, only: [:update]
  resources :recipe_ingredients,only:[:update,:destroy]
  resources :breakfasts,only: [:new]
  resources :breakfast_recipes,only: [:create,:destroy]
  resources :lunches,only: [:new]
  resources :lunch_recipes,only: [:create,:destroy]
  resources :dinners,only: [:new]
  resources :dinner_recipes,only: [:create,:destroy]
end

HEM/app/models/breakfast.rb
# frozen_string_literal: true

class Breakfast < ApplicationRecord
  has_many :breakfast_ingredients
  has_many :ingredients, through: :breakfast_ingredients
  has_many :breakfast_recipes
  has_many :recipes, through: :breakfast_recipes
  belongs_to :user
end

HEM/app/models/breakfast_recipe.rb
# frozen_string_literal: true

class BreakfastRecipe < ApplicationRecord
  belongs_to :recipe
  belongs_to :breakfast
end

HEM/app/models/dinner.rb
# frozen_string_literal: true

class Dinner < ApplicationRecord
  belongs_to :user
  has_many :dinner_ingredients
  has_many :ingredients, through: :dinner_ingredients
  has_many :dinner_recipes
  has_many :recipes, through: :dinner_recipes
end

HEM/app/models/dinner_ingredient.rb
# frozen_string_literal: true

class DinnerIngredient < ApplicationRecord
  belongs_to :ingredient
  belongs_to :dinner
end

HEM/app/models/dinner_recipe.rb
# frozen_string_literal: true

class DinnerRecipe < ApplicationRecord
  belongs_to :recipe
  belongs_to :dinner
end

HEM/app/models/draft.rb
# frozen_string_literal: true

class Draft < ApplicationRecord
  has_many :ingredients, through: :draft_ingredients
  has_many :draft_ingredients
end

HEM/app/models/draft_ingredient.rb
# frozen_string_literal: true

class DraftIngredient < ApplicationRecord
  belongs_to :user
  belongs_to :ingredient
end

HEM/app/models/ingredient.rb
# frozen_string_literal: true

class Ingredient < ApplicationRecord
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients
  has_many :draft_ingredients
  has_many :drafts, through: :draft_ingredients
end

HEM/app/models/lunch.rb
# frozen_string_literal: true

class Lunch < ApplicationRecord
  has_many :lunch_ingredients
  has_many :ingredients, through: :lunch_ingredients
  has_many :lunch_recipes
  has_many :recipes, through: :lunch_recipes
  belongs_to :user
end

HEM/app/models/lunch_ingredient.rb
# frozen_string_literal: true

class LunchIngredient < ApplicationRecord
  belongs_to :ingredient
  belongs_to :lunch
end

HEM/app/models/lunch_recipe.rb
# frozen_string_literal: true

class LunchRecipe < ApplicationRecord
  belongs_to :recipe
  belongs_to :lunch
end

HEM/app/models/nutrion.rb
# frozen_string_literal: true

class Nutrion < ApplicationRecord
  has_many :ingredients, through: :nutrion_ingredients
  has_many :nutrion_ingredients
end

HEM/app/models/recipe.rb
# frozen_string_literal: true

class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
  has_many :breakfast_recipes
  has_many :breakfasts, through: :breakfast_recipes
  has_many :lunch_recipes
  has_many :lunches, through: :lunch_recipes
  has_many :dinners, through: :dinner_recipes
  has_many :dinner_recipes
  validates :name, presence: true
  validates :name, length: { maximum: 15 }
  validates :method, presence: true
  validates :method, length: { maximum: 300 }
end

HEM/app/models/recipe_ingredient.rb
# frozen_string_literal: true

class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

HEM/app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  has_many :recipes
  has_many :draft_ingredients
  has_one :breakfast
  has_one :lunch
  has_one :dinner
  attachment :image
  validates :introduction, length: { maximum: 50 }
  validates :name, length: { maximum: 10 }
  validates :name, presence: true
end

HEM/app/controllers/recipes_controller.rb
# frozen_string_literal: true

class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]
  before_action :correct, only: [:edit]
  before_action :set_search_ingredient, only: %i[new create edit update]

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    if @recipe.save
      draft_ingredients = current_user.draft_ingredients.all
      draft_ingredients.each do |draft_ingredient|
        recipe_ingredients = @recipe.recipe_ingredients.new
        recipe_ingredients.ingredient_id = draft_ingredient.ingredient_id
        recipe_ingredients.quantity = draft_ingredient.quantity
        recipe_ingredients.save
      end
      current_user.draft_ingredients.destroy_all
      redirect_to user_path(current_user)
    else
      render 'new'
    end
  end

  def show; end

  def index
    @recipes = Recipe.all
  end

  def edit; end

  def update
    @recipe_ingredients = @recipe.recipe_ingredients
    @draft_ingredients = current_user.draft_ingredients
    if @recipe.update(recipe_params)
      draft_ingredients = current_user.draft_ingredients.all
      draft_ingredients.each do |draft_ingredient|
        recipe_ingredients = @recipe.recipe_ingredients.new
        recipe_ingredients.ingredient_id = draft_ingredient.ingredient_id
        recipe_ingredients.quantity = draft_ingredient.quantity
        recipe_ingredients.save
      end
      current_user.draft_ingredients.destroy_all
      redirect_back(fallback_location: root_path)
    else
      render 'edit'
    end
  end

  def destroy
    @recipe.delete
    redirect_back(fallback_location: root_path)
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :method, :user_id)
  end

  def correct
    redirect_to user_path(current_user) unless @recipe.user.id == current_user.id
  end

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def set_search_ingredient
    @ingredient = Ingredient.search(params[:search])
    @ingredient = @ingredient.page(params[:page]).per(5)
  end
end

HEM/app/helpers/dinners_helper.rb
# frozen_string_literal: true

module DinnersHelper
end

HEM/app/helpers/drafts_helper.rb
# frozen_string_literal: true

module DraftsHelper
end

HEM/app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

HEM/app/helpers/lunches_helper.rb
# frozen_string_literal: true

module LunchesHelper
end

HEM/app/helpers/new_helper.rb
# frozen_string_literal: true

module NewHelper
end

HEM/app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

HEM/app/views/recipes/edit.html.erb
<div class = "container-fluid">
  <div class = "row">
    <% if @recipe.errors.any? %>
      <h2><%= "エラーが発生しました" %></h2>
        <ol>
          <% @recipe.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ol>
    <% end %>
  </div>
  <div class = "row">
    <div class = "col-xs-3 col-sm-3 col-md-3 col-lg-3 col-xl-3">
      <%= form_with model:@recipe, local:true do |f| %>
        <h3 class = "mb-5 mt-5"><span class ="border border-dark rounded pt-2 pb-2 pr-3 pl-3">レシピ名</span></h3>
        <%= f.text_field :name,class:"rounded",style:"width:150px" %>
        <h3 class = "mb-5 mt-5"><span class ="border border-dark rounded pt-2 pb-2 pr-3 pl-3">調理手順</span></h3>
        <%= f.text_area :method,class:"rounded",style:"width:150px;height:300px" %></br>
        <%= f.submit "投稿", class: "btn btn-secondary mt-3",style:"width:150px"  %>
      <% end %>
    </div>
    <div class = "col-xs-9 col-sm-9 col-md-9 col-lg-9 col-xl-9">
      <h3 class = "mb-5 mt-5"><span class ="border border-dark rounded pt-2 pb-2 pr-3 pl-3">使用食材</span></h3>
      <table>
        <thead>
          <tr>
            <td>食材</td>
            <td>分量</td>
            <td></td>
          </tr>
        </thead>
        <tbody>
        <% recipe_ingredients = @recipe.recipe_ingredients %>
        <% recipe_ingredients.each do |recipe_ingredient| %>
          <%= form_with model:recipe_ingredient, url:recipe_ingredient_path(recipe_ingredient), local:true do |f| %>
            <tr class = "border-top border-bottom  border-dark">
              <td class = "pt-2 pb-2"><%= recipe_ingredient.ingredient.name %></td>
              <td class = "pt-2 pb-2"><%=f.text_field :quantity,:size => "1"  %>　g　</td>
              <td class = "pt-2 pb-2"><%= f.submit "確定", class: "btn btn-secondary",style:"width:100px" %></td>
              <td class = "pt-2 pb-2 pl-2"><%= link_to "削除", recipe_ingredient_path(recipe_ingredient.id),method: :delete,class: "btn btn-dark",style:"width:100px"%></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<%= render partial: "layouts/footer" %>

HEM/app/views/recipes/index.html.erb
<html>
  <body>
<div class =" wrapper container-fluid">  
  <div class = "row">
    <div class = "col-xs-10 col-sm-10 col-md-10 col-lg-10 col-xl-10">
      <h3 class = "mt-5 mb-5"><span class="border border-dark p-2 rounded">投稿レシピ一覧</span></h3>
      <table>
        <thead>
          <tr class>
            <td></td>
            <td class="p-2">投稿者</td>
            <td class="p-2">レシピ名</td>
            <td></td>
          </tr>
        </thead>
        <tbody>
        <% @recipes.each do |recipe| %>
          <tr class="border-top border-bottom border-dark">
            <td class="pt-2 pb-2"><%= attachment_image_tag recipe.user, :image,size:'50x50',fallback: "user.png"%></td>
            <td class="pr-2 pl-2"><%= link_to "#{recipe.user.name}",user_path(recipe.user),class:"text-dark"%></td>
            <td class="pr-2 pl-2"><%= link_to "#{recipe.name}",recipe_path(recipe),class:"text-dark" %></td>
            <% if recipe.user_id == current_user.id %>
            <td class="pl-2">
              <%= link_to edit_recipe_path(recipe.id),class: "btn btn-secondary p-1" do %>
                編集
              <% end %>
            </td>
            <% else %>
            <td class="pl-2"></td>
            <% end %>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="push"></div>
</div>
<%= render partial: "layouts/footer" %>  
</body>
</html>
  

HEM/app/views/recipes/new.html.erb
<div class = "container-fluid">
  <div class = "row">
    <% if @recipe.errors.any? %>
      <h2><%= "エラーが発生しました" %></h2>
        <ol>
          <% @recipe.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ol>
    <% end %>
  </div>
  <div class = "row">
    <div class = "col-md-8 col-lg-8 col-xl-9">
      <div class = "row">
        <div class = "col-md-12 col-lg-12 col-xl-5">
          <h4 class = "mt-5 mb-5"><span class = "border border-dark rounded pt-2 pb-2 pr-3 pl-3">食材検索</h4>
          <%= form_tag(new_recipe_path, :method=>"get") do %>
            <%= text_field_tag :search,"",class:"rounded",style:"width:125px" %>
            <br><%= button_tag :type => "Serch",class:"rounded mt-3 btn btn-secondary",style:"width:125px" do %>
              <i class="fas fa-search"></i>　Search
            <% end %>
          <% end %>
          <h4 class = "mb-5 mt-5"><span class = "border border-dark rounded pt-2 pb-2 pr-3 pl-3">検索結果</span></h4>
          <table>
            <tr>
              <td></td>
              <td></td>
            </tr>
          <% @ingredient.each do |ingredient| %>
            <tr>
              <td>
                <%= ingredient.name %>
              </td>
              <td>
                <div class = "a">
                  <%= button_to "追加", {controller: 'draft_ingredients', action: 'create' }, {method: :post, params: {ingredient_id: ingredient.id}} %>
                </div>
                <div></div>
              </td>
            </tr>
            <% end %>
          </table>
          <div class = "pt-2"><%= paginate @ingredient %></div>
          <%= form_with model:@recipe, local:true do |f| %>
            <h4 class = "mb-5 mt-5"><span class = "border border-dark rounded pt-2 pb-2 pr-3 pl-3">レシピ名</span></h4>
            <%= f.text_field :name,class:"rounded",style:"width:125px" %>
            <h4 class = "mb-5 mt-5"><span class = "border border-dark rounded pt-2 pb-2 pr-3 pl-3">調理手順</span></h4>
            <%= f.text_area :method, class: "rounded",style:"width:125px;height:300px" %></br>
            <%= f.button :type => "submit", class: "btn btn-secondary mt-3",style:"width:125px" do %>
              <i class="far fa-plus-square">　投稿する</i>
            <% end %>
          <% end %>
        </div>
        <div class = "col-md-12 col-lg-12 col-xl-5">
          <h4 class = "mb-5 mt-5"><span class = "border border-dark rounded pt-2 pb-2 pr-3 pl-3">使用食材</span></h4>
          <table>
            <thead>
              <tr>
                <td>食材</td>
                <td>分量</td>
                <td></td>
                <td></td>
              </tr>
            </thead>
            <tbody>
            <% draft_ingredients = current_user.draft_ingredients %>
            <% draft_ingredients.each do |draft_ingredient| %>
              <tr class = "border-top border-bottom  border-dark">
                <td class = "pt-2 pb-2"><%= draft_ingredient.ingredient.name %></td>
                <%= form_with model:draft_ingredient, local:true do |f| %>
                <td class = "pt-2 pb-2"><%=f.text_field :quantity,style:"width:40px" %>　g</td>
                <td><%= f.submit "確定", class: "btn btn-secondary",style:"width:60px" %></td>
                <% end %>
                <td class = "pt-2 pb-2"><%= link_to "削除", draft_ingredient_path(draft_ingredient.id), method: :delete, class: "btn btn-dark",style:"width:60px" %></td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class = "col-md-4 col-lg-4 col-xl-3 border1">
      <h4 class = "mb-5 mt-5"><span class = "border border-dark rounded pt-2 pb-2 pr-3 pl-3">★使用方法</span></h4>
      <h4>1.食材を検索→追加</h4>
      <h4>2.食材の数量を入力→確定</h4>
      <h4>3.レシピ名を入力</h4>
      <h4>4.調理手順を入力</h4>
      <h4>5.投稿ボタン</h4></br>
      <h4>レシピを食事記録に登録!</h4>
    </div>
  </div>
</div>
<%= render partial: "layouts/footer" %>

HEM/app/views/recipes/show.html.erb
<div class = "container-fluid">
  <div class = "row">
    <div class =  "col-xs-3 col-sm-3 col-md-3 col-lg-3 col-xl-3">
      <%= form_with model:@recipe, local:true do |f| %>
        <h3 class = "mb-5 mt-5"><span class ="border border-dark rounded pt-2 pb-2 pr-3 pl-3">レシピ名</span></h3>
        <%= f.text_field :name,:readonly => true,class:"rounded",style:"width:150px" %>
        <h3 class = "mb-5 mt-5"><span class ="border border-dark rounded pt-2 pb-2 pr-3 pl-3">調理手順</span></h3>
        <%= f.text_area :method,:readonly => true,class:"rounded",style:"width:150px;height:300px" %></br>
      <% end %>
    </div>
    <div class = "col-xs-9 col-sm-9 col-md-9 col-lg-9 col-xl-9">
      <h3 class = "mb-5 mt-5"><span class ="border border-dark rounded pt-2 pb-2 pr-3 pl-3">使用食材</span></h3>
      <table>
        <thead>
          <tr>
            <td>食材</td>
            <td>分量</td>
          </tr>
        </thead>
        <tbody>
          <% recipe_ingredients = @recipe.recipe_ingredients %>
          <% recipe_ingredients.each do |recipe_ingredient| %>
            <tr class = "border-top border-bottom  border-dark">
              <td class = "pt-2 pb-2"><%= recipe_ingredient.ingredient.name %></td>
              <%= form_with model:recipe_ingredient, local:true do |f| %>
                <td class = "pt-2 pb-2"><%= f.text_field :quantity,:size => "1",:readonly => true %> g </td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<%= render partial: "layouts/footer" %>